debug: false
server:
  port: 8080
  servlet:
    context-path: /
---
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: hemanthjamili
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.H2Dialect